name: FitrackPro Pipeline - Development

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and test
        run: |
          dotnet build --configuration Debug --no-restore
          dotnet test --no-restore --verbosity normal

      # Additional steps specific to development environment
